service: reactionary

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-1

  environment:
    TOKEN: "${env:TOKEN}"

package:
  exclude:
    - .env

functions:
  api:
    handler: src/index.handler

    events:
     - http:
        method: GET
        path: /{id}
     - http:
        method: GET
        path: /

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  webpackIncludeModules: true # enable auto-packing of external modules
  dotenv:
    path: .env
    include:
      - TOKEN
  customDomain:
    domainName: api.theweb.rocks
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: '*.theweb.rocks'
